using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using UsageApp.Controls;
using UsageApp.Theme;
using UsageCore;
using UsageCore.Model;
using UsageCore.View;

namespace UsageApp.Views;

/// <summary>
/// Activity at a glance: twelve cards, read as three rows of four - what was
/// run, what it consumed, when. Four FIXED columns stepping 4 to 2 to 1, never
/// auto-fit, because a count that drifts with the window scrambles the rows.
/// </summary>
public static class ScoreCards
{
    private sealed record Card(string Label, string Icon, UIElement Value, string? Sub, bool ClipSub = false, string? Tip = null);

    public static FitGrid Build(ProviderMeta meta, ActivityStats activity, UsageCell combined)
    {
        var written = combined.CacheWrite5m + combined.CacheWrite1h;
        var cachedTotal = combined.CacheRead + written;
        var messagesLabel = char.ToUpperInvariant(meta.MessageNoun[0]) + meta.MessageNoun[1..];

        // "Aug 11 · My App": date first, because this line is clipped rather
        // than wrapped, and a long project name should lose its tail, not the date.
        string RecordSub(SessionRecord? record)
        {
            if (record is null) return "nothing recorded yet";
            var parts = new List<string>();
            if (record.Date is { } date) parts.Add(Format.DateShort(date));
            parts.Add(record.ProjectName);
            if (record.IsSubagent) parts.Add(meta.SubagentNoun);
            return string.Join(" · ", parts);
        }

        TextBlock Count(double value, Func<double, string> format) =>
            CountUp.Apply(Ui.Text("", 30, 640, Palette.TextBrush, -0.022, numeric: true), value, format);

        UIElement TopModel()
        {
            if (activity.FavoriteModel is not { } model) return Ui.Text("—", 30, 640);
            var panel = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 10 };
            panel.Children.Add(Ui.Swatch(Palette.ModelColor(model)));
            panel.Children.Add(Ui.Text(Format.Model(model), 30, 640, Palette.ModelBrush(model), -0.022));
            return panel;
        }

        var peak = activity.PeakSession;
        Card[] cards =
        [
            // Row 1: what was run
            new("Sessions", "sessions", Count(activity.Sessions, Format.Count),
                $"{Format.Count(activity.Sessions - activity.SubagentSessions)} top-level · {Format.Count(activity.SubagentSessions)} {meta.SubagentNoun}", Tip: meta.SessionTip),
            new(messagesLabel, "messages", Count(activity.Messages, Format.Count), "de-duplicated API calls", Tip: meta.MessageTip),
            new("Longest chat", "hourglass",
                activity.LongestSession is { } longest ? Count(longest.RuntimeSeconds, Format.Duration) : Ui.Text("—", 30, 640),
                RecordSub(activity.LongestSession), ClipSub: true,
                Tip: "The most active runtime in a single chat, measured the same way as total runtime: gaps between consecutive log lines, dropping any longer than the idle cutoff. Not first-to-last wall clock, which mostly measures leaving a session open. " +
                     $"Time spent by {meta.SubagentNoun} threads is not added on top — they run inside this chat’s wall clock, so it is already counted."),
            new("Top model", "model", TopModel(), "by total tokens"),

            // Row 2: what it consumed
            new("Input tokens", "input", Count(combined.Input, Format.Tokens), "uncached prompt",
                Tip: "Prompt tokens charged at the full input rate. Anything served from cache is counted under Cached tokens instead, which is why this figure looks small next to it."),
            new("Output tokens", "output", Count(combined.Output, Format.Tokens),
                meta.HasReasoningTokens ? $"incl. {Format.Tokens(combined.Reasoning ?? 0)} reasoning" : "generated",
                Tip: meta.HasReasoningTokens
                    ? "Tokens generated by the model — the most expensive bucket per token. Reasoning tokens are already inside this figure and billed at the same rate, so they are not added on top."
                    : "Tokens generated by the model — the most expensive bucket per token."),
            new("Cached tokens", "cache", Count(cachedTotal, Format.Tokens),
                meta.HasCacheWrites ? $"{Format.Tokens(combined.CacheRead)} read · {Format.Tokens(written)} written" : "prompt served from cache",
                Tip: meta.HasCacheWrites
                    ? "Cache reads plus cache writes. Reads are billed at roughly a tenth of the input rate and writes at a premium, but the sheer volume of reads makes this the largest driver of total cost."
                    : "Prompt tokens served from cache, billed at a tenth of the input rate. Codex resends the whole conversation every turn, so this is nearly all of the prompt — and, despite the discount, where most of the cost sits."),
            new("Peak tokens", "peak",
                peak is not null ? Count(peak.TotalTokens, Format.Tokens) : Ui.Text("—", 30, 640),
                RecordSub(peak), ClipSub: true,
                Tip: peak is not null
                    ? $"The heaviest single chat: {Format.Tokens(peak.TotalTokens)} tokens costing {Format.Usd(peak.CostUsd)}, in {peak.ProjectName}"
                      + (peak.SubagentThreads > 0 ? $", including the {Format.Count(peak.SubagentThreads)} {meta.SubagentNoun} thread(s) it spawned" : "")
                      + ". Every bucket, after de-duplication. Read from the transcripts still on disk, so unlike the totals above it is not restored from the archive."
                    : "The heaviest single chat, once there is one."),

            // Row 3: when
            new("Active days", "calendar", Count(activity.ActiveDays, Format.Count), "days with any usage"),
            new("Current streak", "flame", Count(activity.CurrentStreakDays, v => $"{Math.Round(v)}d"), "consecutive days",
                Tip: "Consecutive active days ending today. Resets to zero once a full day passes with no usage."),
            new("Longest streak", "trophy", Count(activity.LongestStreakDays, v => $"{Math.Round(v)}d"), "consecutive days"),
            new("Peak hour", "clock", Ui.Text(Format.Hour(activity.PeakHour), 30, 640, numeric: true), $"most {meta.MessageNoun}",
                Tip: "Busiest hour of the day by message count, in your configured local offset (settings.json)."),
        ];

        // Container steps, as the original's container query: a card falls
        // under ~210px, and starts wrapping its own label, below these widths.
        var grid = new FitGrid(width => width > 900 ? 4 : width > 450 ? 2 : 1) { Gap = 14, Margin = new Thickness(0, 0, 0, 26) };
        for (var i = 0; i < cards.Length; i++)
        {
            var card = cards[i];
            var stack = new StackPanel();
            var label = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 7, Margin = new Thickness(0, 0, 0, 7) };
            var iconBrush = new Microsoft.UI.Xaml.Media.SolidColorBrush(Palette.TextFaint);
            var icon = ScoreIcons.Create(card.Icon, iconBrush);
            icon.Opacity = 0.72;
            label.Children.Add(icon);
            label.Children.Add(Ui.Text(card.Label, 13.5, 500, Palette.TextFaintBrush));
            if (card.Tip is not null) label.Children.Add(Ui.InfoTip($"About {card.Label.ToLowerInvariant()}", card.Tip));
            stack.Children.Add(label);
            stack.Children.Add(card.Value);
            if (card.Sub is not null)
            {
                var sub = Ui.Text(card.Sub, 13, 400, Palette.TextFaintBrush);
                sub.Margin = new Thickness(0, 5, 0, 0);
                if (card.ClipSub) Ui.SetTip(sub, card.Sub);
                stack.Children.Add(sub);
            }
            var border = Ui.Card(stack, new Thickness(20, 18, 20, 18), hover: true);
            // The icon takes the agent's accent on hover.
            border.PointerEntered += (_, _) => { iconBrush.Color = Palette.AccentColor; icon.Opacity = 1; };
            border.PointerExited += (_, _) => { iconBrush.Color = Palette.TextFaint; icon.Opacity = 0.72; };
            Ui.Rise(border, i * 35);
            grid.Children.Add(border);
        }
        return grid;
    }
}
